version: '3'

volumes:
  certs:
  conf:
  db:
  html:
  nextcloud_config:
  nextcloud_data:
  nextcloud_db:
  nextcloud_html:

services:
  db:
    image: postgres:12.1-alpine
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-databases.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: '.env'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    restart: always

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  gen:
    image: jwilder/docker-gen:0.7.0
    container_name: nginx-proxy-gen
    depends_on:
      - collabora
      - nextcloud
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - gen
      - nginx
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d

  nextcloud:
    build: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_db:/var/lib/postgresql/data
      - nextcloud_html:/var/www/html
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE_NEXCLOUD}
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - LETSENCRYPT_HOST=${HOST_NEXTCLOUD}
      - VIRTUAL_HOST=${HOST_NEXTCLOUD}

  collabora:
    image: collabora/code:6.4.10.10
    container_name: collabora
    restart: always
    depends_on:
      - nextcloud
    restart: always
    cap_add:
      - MKNOD
    environment:
      - domain=${COLLABORA_DOMAIN}
      - username=${COLLABORA_USER}
      - password=${COLLABORA_PASSWORD}
      - dictionaries=${COLLABORA_DICTIONARIES}
      - VIRTUAL_HOST=${HOST_COLLABORA}
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${HOST_COLLABORA}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
    expose:
      - 9980

  coturn:
    build: coturn
    container_name: coturn
    restart: always
    env_file: '.env'
    network_mode: 'host'
