version: '3'

volumes:
  certs:
  conf:
  db:
  html:
  nextcloud_config:
  nextcloud_data:
  nextcloud_db:
  nextcloud_html:
  onlyoffice_data:
  onlyoffice_log:

services:
  db:
    image: postgres:12.1-alpine
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init-databases.sh:/docker-entrypoint-initdb.d/init.sh
    env_file: '.env'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    restart: always

  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  gen:
    image: jwilder/docker-gen:0.7.0
    container_name: nginx-proxy-gen
    depends_on:
      - onlyoffice
      - nextcloud
      - nginx
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./nginx-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    depends_on:
      - gen
      - nginx
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
    volumes:
      - certs:/etc/nginx/certs
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx-proxy/vhost.d:/etc/nginx/vhost.d

  nextcloud:
    build: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - nextcloud_config:/var/www/html/config
      - nextcloud_data:/var/www/html/data
      - nextcloud_db:/var/lib/postgresql/data
      - nextcloud_html:/var/www/html
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE_NEXCLOUD}
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - LETSENCRYPT_HOST=${HOST_NEXTCLOUD}
      - VIRTUAL_HOST=${HOST_NEXTCLOUD}

  onlyoffice:
    image: onlyoffice/documentserver:6.2.1
    container_name: onlyoffice
    restart: always
    expose:
      - "80"
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
    environment:
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DATABASE_ONLYOFFICE}
      - DB_PORT=5432
      - DB_PWD=${POSTGRES_PASSWORD}
      - DB_USER=${POSTGRES_USER}
      - LETSENCRYPT_EMAIL=${SSL_EMAIL}
      - LETSENCRYPT_HOST=${HOST_ONLYOFFICE}
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - VIRTUAL_HOST=${HOST_ONLYOFFICE}

  onlyoffice-rabbitmq:
    image: rabbitmq:3.8.14
    container_name: onlyoffice-rabbitmq
    restart: always

  coturn:
    build: coturn
    container_name: coturn
    restart: always
    env_file: '.env'
    network_mode: 'host'
